import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterContext from "@/app/context/ToasterContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
        <link rel="icon" href="/images/logo.png" type="image/png" title="Favicon" />
      </head>
      <body className={inter.className}>
<ToasterContext/>
      {children}
      </body>
      </html>
  )
}
